// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOy-j0a2eOMHL_bqII8CBi_M94IwdsbCA',
    appId: '1:620518990768:web:6881f54142f11a0365ac75',
    messagingSenderId: '620518990768',
    projectId: 'movie-app-6f399',
    authDomain: 'movie-app-6f399.firebaseapp.com',
    storageBucket: 'movie-app-6f399.firebasestorage.app',
    measurementId: 'G-FS5E7F87YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEeoxbVUJINaiTAQdtZYmUiaAjGWxeAD0',
    appId: '1:620518990768:android:6cd62d3293c1d95a65ac75',
    messagingSenderId: '620518990768',
    projectId: 'movie-app-6f399',
    storageBucket: 'movie-app-6f399.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoOobHkowjH8-nbg-eudGf7PA7IbyFCmc',
    appId: '1:620518990768:ios:1fab22cd3ee020ac65ac75',
    messagingSenderId: '620518990768',
    projectId: 'movie-app-6f399',
    storageBucket: 'movie-app-6f399.firebasestorage.app',
    iosClientId: '620518990768-pefhsj9gj2fvt4chm7p0kagp5j16fkfo.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOy-j0a2eOMHL_bqII8CBi_M94IwdsbCA',
    appId: '1:620518990768:web:d7f35d49ab79410965ac75',
    messagingSenderId: '620518990768',
    projectId: 'movie-app-6f399',
    authDomain: 'movie-app-6f399.firebaseapp.com',
    storageBucket: 'movie-app-6f399.firebasestorage.app',
    measurementId: 'G-6BK5NZ00BM',
  );
}
